name: device_preview
version: 0.7.4
description: Approximate how your Flutter app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=2.12.0 <3.0.0' 

dependencies:
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.2
  path_provider: ^2.0.9
  device_frame: ^1.0.0
  font_awesome_flutter: ^10.1.0
  http: ^0.13.4
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.13
  pedantic: ^1.11.1
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  analyzer: ^3.4.1
